import { copyFile, mkdir, readdir, writeFile } from 'node:fs/promises';
import { basename, dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { compileCommonloom } from 'commonloom';

const currentFile = fileURLToPath(import.meta.url);
const sharedRoot = resolve(dirname(currentFile), '..');
const repositoryRoot = resolve(sharedRoot, '..', '..');
const contentRoot = join(sharedRoot, 'content');
const assetRoot = join(sharedRoot, 'assets');

const targetRoot = resolve(process.argv[2] ?? process.cwd());
const moduleOutput = resolve(
  process.argv[3] ?? join(targetRoot, 'src', 'generated', 'commonloom-content.ts'),
);
const publicAssetRoot = resolve(
  process.argv[4] ?? join(targetRoot, 'public', 'commonloom-assets'),
);

const contentFiles = (await readdir(contentRoot))
  .filter((fileName) => fileName.endsWith('.md'))
  .sort();

const manifests = contentFiles.map((fileName) => ({
  id: fileName.replace(/\.md$/, ''),
  sourcePath: fileName,
}));

const result = await compileCommonloom({
  copyRoot: contentRoot,
  mediaRoot: assetRoot,
  manifests,
  html: {
    allowInlineHtml: false,
  },
  links: {
    resolveLink({ rawTarget }) {
      if (rawTarget.startsWith('./')) {
        return {
          kind: 'internal',
          resolvedTarget: `#${rawTarget.replace(/^\.\/|\.md$/g, '')}`,
        };
      }

      return {
        kind: 'external',
        resolvedTarget: rawTarget,
      };
    },
  },
});

await mkdir(dirname(moduleOutput), { recursive: true });
await mkdir(publicAssetRoot, { recursive: true });

for (const assetName of await readdir(assetRoot)) {
  await copyFile(join(assetRoot, assetName), join(publicAssetRoot, assetName));
}

const assetBasePath = '/commonloom-assets';
const documents = (result.documents ?? []).map((document) => ({
  id: document.manifest.id,
  title: getFrontmatterString(document.frontmatter, 'title', document.manifest.id),
  summary: getFrontmatterString(document.frontmatter, 'summary', ''),
  tags: getFrontmatterStrings(document.frontmatter, 'tags'),
  heroImage: getFrontmatterAsset(document.frontmatter, 'heroImage'),
  bodyHtml: document.bodyHtml,
  trace: {
    contentHash: document.sourceTrace.contentHash,
    headings: document.sourceTrace.headings,
    links: document.sourceTrace.links,
    images: document.sourceTrace.images,
  },
}));

const generated = `// Generated by examples/shared/scripts/generate-content.mjs.
// Do not edit directly; run the example package's generate script.

export const commonloomAssetBasePath = ${JSON.stringify(assetBasePath)};
export const commonloomDocuments = ${JSON.stringify(documents, null, 2)} as const;
export const commonloomDiagnostics = ${JSON.stringify(result.diagnostics, null, 2)} as const;
`;

await writeFile(moduleOutput, generated, 'utf8');

const displayPath = relative(repositoryRoot, moduleOutput).replaceAll('\\', '/');
console.log(`Generated ${displayPath}`);

function getFrontmatterString(frontmatter, key, fallback) {
  if (isRecord(frontmatter) && typeof frontmatter[key] === 'string') {
    return frontmatter[key];
  }

  return fallback;
}

function getFrontmatterStrings(frontmatter, key) {
  if (
    isRecord(frontmatter) &&
    Array.isArray(frontmatter[key]) &&
    frontmatter[key].every((item) => typeof item === 'string')
  ) {
    return frontmatter[key];
  }

  return [];
}

function getFrontmatterAsset(frontmatter, key) {
  const value = getFrontmatterString(frontmatter, key, '');

  if (!value) {
    return '';
  }

  return `${assetBasePath}/${basename(value)}`;
}

function isRecord(value) {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}
